name: CD

on: 
  push:
    tags: 'v*'

jobs:
  build-linux:
    runs-on: ubuntu-18.04
    container: "geodesolutions/centos"
    strategy:
      matrix:
        config:
        - {python: "3.6", tag: "cp36-cp36m", dir: "3.6m"}
        - {python: "3.7", tag: "cp37-cp37m", dir: "3.7m"}
        - {python: "3.8", tag: "cp38-cp38", dir: "3.8"}
        - {python: "3.9", tag: "cp39-cp39", dir: "3.9"}
        - {python: "3.10", tag: "cp310-cp310", dir: "3.10"}

    steps:
    - uses: actions/checkout@v1
    - name: Cache node modules
      uses: actions/cache@v1.2.0
      with:
        path: node_modules
        key: node-rhel-${{ matrix.config.python }}-${{ hashFiles('package-lock.json') }}
    - name: Generate package
      id: package
      run: |
        version="${GITHUB_REF##*/*/v}"
        echo ::set-output name=version::$version-python${{ matrix.config.python }}
        export VERSION=$version-python${{ matrix.config.python }}
        npm config set cmake_PYTHON_VERSION ${{ matrix.config.python }}
        npm install
        npm run electron:package
      env:
        PLATFORM: "linux"
        Python3_EXECUTABLE: /opt/python/${{ matrix.config.tag }}/bin/python${{ matrix.config.dir }}
        Python3_INCLUDE_DIR: /opt/python/${{ matrix.config.tag }}/include/python${{ matrix.config.dir }}
    - name: Upload
      uses: softprops/action-gh-release@v1
      with:
        files: "dist_electron/geode-${{ steps.package.outputs.version }}-linux.zip"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Notify slack
      if: failure() && github.ref == 'refs/heads/master'
      uses: 8398a7/action-slack@v2
      with:
        status: failure
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  build-windows:
    runs-on: windows-2016
    strategy:
      matrix:
        config:
        - {python: "3.6", tag: "cp36-cp36m"}
        - {python: "3.7", tag: "cp37-cp37m"}
        - {python: "3.8", tag: "cp38-cp38"}
        - {python: "3.9", tag: "cp39-cp39"}
        - {python: "3.10", tag: "cp310-cp310"}

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.config.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.config.python }}
    - name: Cache node modules
      uses: actions/cache@v1.2.0
      with:
        path: node_modules
        key: node-win64-${{ matrix.config.python }}-${{ hashFiles('package-lock.json') }}
    - name: Generate package
      id: package
      run: |
        $version = ${env:GITHUB_REF} -replace 'refs\/tags\/v', ''
        echo "::set-output name=version::$version-python${{ matrix.config.python }}"
        $env:VERSION = "$version-python${{ matrix.config.python }}"
        npm config set cmake_PYTHON_VERSION ${{ matrix.config.python }}
        npm install
        npm run electron:package
      env:
        PLATFORM: "win64"
        Python3_ROOT_DIR: ${{ env.pythonLocation }}
        CSC_LINK: ${{ secrets.CODE_SIGN_CERTIFICATE }}
        CSC_KEY_PASSWORD: ${{ secrets.CODE_SIGN_PASSWORD }}
    - name: Upload
      uses: softprops/action-gh-release@v1
      with:
        files: "dist_electron/geode-${{ steps.package.outputs.version }}-win64.zip"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Notify slack
      if: failure() && github.ref == 'refs/heads/master'
      uses: 8398a7/action-slack@v2
      with:
        status: failure
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
