name: CI

on: 
  push:
  pull_request:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    container: "ghcr.io/geode-solutions/centos:master"
    strategy:
      matrix:
        config:
        - {python: "3.8", tag: "cp38-cp38"}
        - {python: "3.9", tag: "cp39-cp39"}
        - {python: "3.10", tag: "cp310-cp310"}

    steps:
    - uses: actions/checkout@v1
    - name: Cache node modules
      uses: actions/cache@v1.2.0
      with:
        path: node_modules
        key: node-rhel-${{ matrix.config.python }}-${{ hashFiles('package-lock.json') }}
    - name: Compile
      run: |
        npm install
        npm run electron:package
      env:
        VERSION: "unknown"
        PLATFORM: "linux"
        PYTHON_EXE: /opt/python/${{ matrix.config.tag }}/bin/python
    - name: Notify slack
      if: failure() && github.ref == 'refs/heads/master'
      uses: 8398a7/action-slack@v2
      with:
        status: failure
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      
  build-windows:
    runs-on: windows-2019
    strategy:
      matrix:
        config:
        - {python: "3.8", tag: "cp38-cp38"}
        - {python: "3.9", tag: "cp39-cp39"}
        - {python: "3.10", tag: "cp310-cp310"}

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Set up Python ${{ matrix.config.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.config.python }}
    - name: Cache node modules
      uses: actions/cache@v1.2.0
      with:
        path: node_modules
        key: node-win64-${{ matrix.config.python }}-${{ hashFiles('package-lock.json') }}
    - name: Compile
      run: |
        npm install
        npm run electron:package
      env:
        VERSION: "unknown"
        PLATFORM: "win64"
        PYTHON_EXE: ${{ env.pythonLocation }}/python
    - name: Notify slack
      if: failure() && github.ref == 'refs/heads/master'
      uses: 8398a7/action-slack@v2
      with:
        status: failure
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      
  semantic-release:
    runs-on: ubuntu-latest
    needs: [build-linux, build-windows]
    steps:
    - uses: actions/checkout@v1
    - run: npx semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
