name: CI

on: 
  push:
  pull_request:

jobs:
  build-linux:
    runs-on: ubuntu-18.04
    container: "geodesolutions/centos"
    strategy:
      matrix:
        config:
        - {python: "3.6", tag: "cp36-cp36m", dir: "3.6m",}
        - {python: "3.7", tag: "cp37-cp37m", dir: "3.7m",}
        - {python: "3.8", tag: "cp38-cp38", dir: "3.8",}
        - {python: "3.9", tag: "cp39-cp39", dir: "3.9",}
        - {python: "3.10", tag: "cp310-cp310", dir: "3.10",}

    steps:
    - uses: actions/checkout@v1
    - name: Cache node modules
      uses: actions/cache@v1.2.0
      with:
        path: node_modules
        key: node-rhel-${{ matrix.config.python }}-${{ hashFiles('package-lock.json') }}
    - name: Compile
      run: |
        echo $Python3_INCLUDE_DIRS
        ls $Python3_INCLUDE_DIRS
        npm config set cmake_PYTHON_VERSION ${{ matrix.config.python }}
        npm install
        npm run electron:package
      env:
        VERSION: "unknown"
        PLATFORM: "rhel"
        Python3_ROOT_DIR: /opt/python/${{ matrix.config.tag }}
        Python3_INCLUDE_DIRS: /opt/python/${{ matrix.config.tag }}/include/python${{ matrix.config.dir }}
    - name: Notify slack
      if: failure() && github.ref == 'refs/heads/master'
      uses: 8398a7/action-slack@v2
      with:
        status: failure
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      
  build-windows:
    runs-on: windows-2016
    strategy:
      matrix:
        config:
        - {python: "3.6", tag: "cp36-cp36m"}
        - {python: "3.7", tag: "cp37-cp37m"}
        - {python: "3.8", tag: "cp38-cp38"}
        - {python: "3.9", tag: "cp39-cp39"}
        - {python: "3.10", tag: "cp310-cp310"}

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.config.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.config.python }}
    - name: Cache node modules
      uses: actions/cache@v1.2.0
      with:
        path: node_modules
        key: node-win64-${{ matrix.config.python }}-${{ hashFiles('package-lock.json') }}
    - name: Compile
      run: |
        npm config set cmake_PYTHON_VERSION ${{ matrix.config.python }}
        npm install
        npm run electron:package
      env:
        VERSION: "unknown"
        PLATFORM: "win64"
        Python3_ROOT_DIR: ${{ env.pythonLocation }}
        CSC_LINK: ${{ secrets.CODE_SIGN_CERTIFICATE }}
        CSC_KEY_PASSWORD: ${{ secrets.CODE_SIGN_PASSWORD }}
    - name: Notify slack
      if: failure() && github.ref == 'refs/heads/master'
      uses: 8398a7/action-slack@v2
      with:
        status: failure
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      
  semantic-release:
    runs-on: ubuntu-18.04
    needs: [build-linux, build-windows]
    steps:
    - uses: actions/checkout@v1
    - run: npx semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
